export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  BURST_UNVERIFIED: "BURST_UNVERIFIED",
  CREW_DAY_CONFLICT: "CREW_DAY_CONFLICT",
  ACCEPTANCE_FAILED: "ACCEPTANCE_FAILED",
  STOCK_INSUFFICIENT: "STOCK_INSUFFICIENT",
  ORDER_STATE_INVALID: "ORDER_STATE_INVALID"
} as const;
