export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  POINT_NOT_FOUND: "POINT_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  BURST_UNVERIFIED: "BURST_UNVERIFIED",
  VERIFY_REJECTED: "VERIFY_REJECTED",
  ORDER_ALREADY_OPEN: "ORDER_ALREADY_OPEN",
  CREW_DAY_CONFLICT: "CREW_DAY_CONFLICT",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  ACCEPTANCE_FAILED: "ACCEPTANCE_FAILED",
  ORDER_STATE_INVALID: "ORDER_STATE_INVALID",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;
